# -*- coding: utf-8 -*-
"""color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF-XLaUsnFvNqzvDPfqj1SQgsBV9e5cV
"""

import requests

def get_palette(keyword):
    url = f"https://colormagic.app/api/palette/search?q={keyword}"
    res = requests.get(url)
    res.raise_for_status()
    return res.json()

print(get_palette("green")[0])