# -*- coding: utf-8 -*-
"""Copy of color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bJoghMhCeXhfjrFUqsCsKZFTfzb5w0s
"""

import requests
import matplotlib.pyplot as plt

def get_palette(keyword):
    url = f"https://colormagic.app/api/palette/search?q={keyword}"
    res = requests.get(url)
    res.raise_for_status()
    return res.json()

# 🔹 Ask the user for input
keyword = input("Enter a color theme keyword (e.g. green, sunset, pastel): ").strip()

data = get_palette(keyword)[0]
colors = data["colors"]

# 🔹 Draw color blocks with labels
n = len(colors)
fig, ax = plt.subplots(figsize=(1.6 * n, 2.5))

for i, c in enumerate(colors):
    ax.add_patch(plt.Rectangle((i + 0.05, 1), 0.9, 1, color=c))
    ax.text(i + 0.5, 0.8, c, ha='center', va='top', fontsize=10)

ax.set_xlim(0, n)
ax.set_ylim(0, 2.2)
ax.axis('off')

plt.show()